name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Super Linter
        uses: github/super-linter@v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_SECRETS: false
